{
 "title": "nwaku-monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nwaku_instance",
    "query": {
     "query": "label_values(libp2p_peers, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "# Single Node (Select nwaku-instance)"
   }
  },
  {
   "title": "Message distrubution %/kBytes (Last Hour)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(waku_histogram_message_size_bucket{instance=\"[[nwaku_instance]]\"}[1h])/scalar(rate(waku_histogram_message_size_count{instance=\"[[nwaku_instance]]\"}[1h]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Libp2p Open Streams",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "libp2p_open_streams{instance=\"[[nwaku_instance]]\"}",
     "legendFormat": "{{instance}}_{{type}}"
    }
   ]
  },
  {
   "title": "Connected Protocols",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_connected_peers{instance=\"[[nwaku_instance]]\"}",
     "legendFormat": "{{instance}}_{{protocol}}_{{direction}}"
    }
   ]
  },
  {
   "title": "Connected Streams",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_streams_peers{instance=\"[[nwaku_instance]]\"}",
     "legendFormat": "{{instance}}_{{protocol}}_{{direction}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 20 }, "options": { "content": "# Global View (All Nodes)" } },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inbound Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_connected_peers{direction=\"Inbound\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "waku_connected_peers{direction=\"Outbound\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reachability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_confidence{reachability=\"Reachable\"}",
     "legendFormat": "{{reachability}}"
    }
   ]
  },
  {
   "title": "Num PubSub Topics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_pubsub_topics", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nim_gc_mem_bytes{}", "legendFormat": " " }
   ]
  },
  {
   "title": "libp2p traffic (in)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"in\"}[$__rate_interval])",
     "legendFormat": "{{instance}}_{{direction}}"
    }
   ]
  },
  {
   "title": "libp2p traffic (out)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{direction=\"out\"}[$__rate_interval])",
     "legendFormat": "{{instance}}_{{direction}}"
    }
   ]
  },
  {
   "title": "total traffic cadvisor (in)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}_{{container_label_com_docker_compose_container_number}}"
    }
   ]
  },
  {
   "title": "total traffic cadvisor (out)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}_{{container_label_com_docker_compose_container_number}}"
    }
   ]
  },
  {
   "title": "Rejected Messages/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "(increase(waku_msg_validator_signed_outcome_total{result=\"Reject\"}[1m]))/60",
     "legendFormat": "{{instance}}_{{result}}"
    }
   ]
  },
  {
   "title": "Acepted Messages/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 53 },
   "targets": [
    {
     "expr": "(increase(waku_msg_validator_signed_outcome_total{result=\"Accept\"}[1m]))/60",
     "legendFormat": "{{instance}}_{{result}}"
    }
   ]
  },
  {
   "title": "Average msg size (kBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "waku_histogram_message_size_sum/waku_histogram_message_size_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages/second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 61 },
   "targets": [
    {
     "expr": "(increase(waku_node_messages_total[1m]))/60",
     "legendFormat": "{{instance}}_{{type}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 69 },
   "targets": [
    { "expr": "libp2p_peers", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "Bad Peer Disconnection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 69 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_bad_score_disconnection_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer Store Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 77 },
   "targets": [
    { "expr": "waku_peer_store_size", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "Published Pubsub Messages/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 77 },
   "targets": [
    {
     "expr": "(increase(libp2p_pubsub_messages_published_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Pubsub Messages/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "(increase(libp2p_gossipsub_failed_publish_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GossipSub Invalid Topic Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 85 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_invalid_topic_subscription_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GossipSub Low Peers Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_low_peers_topics",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GossipSub Healthy Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 93 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_healthy_peers_topics",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GossipSub Total Received/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "(increase(libp2p_gossipsub_received_total[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reachability State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 101 },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_confidence{}",
     "legendFormat": "{{instance}}__{{reachability}}"
    }
   ]
  },
  {
   "title": "LibP2P Dials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "libp2p_total_dial_attempts_total{}",
     "legendFormat": "{{instance}}__attempts"
    },
    { "expr": "libp2p_failed_dials_total{}", "legendFormat": "{{instance}}__failed" },
    {
     "expr": "libp2p_successful_dials_total{}",
     "legendFormat": "{{instance}}__success"
    }
   ]
  },
  {
   "title": "Peers Per Topic Mesh",
   "type": "timeseries",
   "description": "Careful with this when using more than one topic, as all values will be added in \"other\" unless nimlibp2p is compiled with the appropriate flags",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 109 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_peers_per_topic_mesh",
     "legendFormat": "{{instance}}_topic_{{topic}}"
    }
   ]
  },
  {
   "title": "Nim Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nim_gc_mem_bytes{}", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "Container Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes",
     "legendFormat": "{{container_label_com_docker_compose_service}}_{{container_label_com_docker_compose_container_number}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 125 },
   "targets": [
    { "expr": "waku_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU (Unsure what)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 125 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}_{{container_label_com_docker_compose_container_number}}"
    }
   ]
  },
  {
   "title": "Store/Archive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waku Store Queries (Postgres) (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "increase(waku_store_queries{instance=~\"nwaku-store-postgres-1:8008\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waku Store Queries (SQLite) (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "increase(waku_store_queries{instance=~\"nwaku-store-sqlite-1:8008\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waku Archive Errors (Postgres) (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "sum by (type)(increase(waku_archive_errors{instance=~\"nwaku-store-postgres-1:8008\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Waku Archive Errors (SQLite) (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "sum by (type)(increase(waku_archive_errors{instance=~\"nwaku-store-sqlite-1:8008\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Waku Archive Query Duration (Postgres)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(waku_archive_query_duration_seconds_bucket{instance=~\"nwaku-store-postgres-1:8008\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Waku Archive Query Duration (SQLite)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(waku_archive_query_duration_seconds_bucket{instance=~\"nwaku-store-sqlite-1:8008\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Waku Archive Insert Duration (Postgres)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(waku_archive_insert_duration_seconds_bucket{instance=~\"nwaku-store-postgres-1:8008\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Waku Archive Insert Duration (SQLite)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(waku_archive_insert_duration_seconds_bucket{instance=~\"nwaku-store-sqlite-1:8008\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}